<?php
/**
 * Created by IntelliJ IDEA.
 * User: shenshijun
 * Date: 15/9/11
 * Time: 上午11:46
 */

namespace app\models;


use yii\base\Model;

class FileUploadForm extends Model
{

    public $file1;
    public function rules()
    {
        return [
        ]; // TODO: Change the autogenerated stub
    }
}